name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm set @netmanagement:registry http://npm.pkg.github.com
      - run: npm set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN
      - run: npm ci
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{secrets.NPM_TOKEN}}